name: 🫣 Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VARIANT: assembleWebsiteFullDebug
    
    steps:
    - name: 🥏 Checkout
      uses: actions/checkout@v4 # Reverted to v4 for stability

    - name: ☕️ JDKv17
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: ⚡️ +x gradlew
      run: chmod +x gradlew

    - name: 🎪 Secrets
      if: success()
      run: |
        mkdir -p app/src/debug
        echo "${GSCV_TEST_JSON}" > app/src/debug/google-services.json
        if [ -z "$GSCV_TEST_JSON" ]; then
          echo "VARIANT=assembleFdroidFullDebug" >> "$GITHUB_ENV"
        fi
      env:
        GSCV_TEST_JSON: ${{ secrets.GOOGLE_SERVICES_TEST_JSON }}

    - name: 🚂 Assemble
      if: success()
      run: |
        ./gradlew \
          ${VARIANT} \
          --info \
          --warning-mode all
      env:
        VARIANT: ${{ env.VARIANT }}

    - name: 🔍 Find APK
      run: find app/build/outputs/apk/ -name "*.apk"

    - name: 📦 Upload APK
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: my-application-apk
        path: app/build/outputs/apk/**/*.apk
